// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDrr6vl_1QCaqghxnNWE8KEo4CgiJ-Gj_g',
    appId: '1:1425969683:web:6672ff1c2b5749e41b25e6',
    messagingSenderId: '1425969683',
    projectId: 'mentorhub-82a2b',
    authDomain: 'mentorhub-82a2b.firebaseapp.com',
    storageBucket: 'mentorhub-82a2b.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBjlaJYMKRSal51X5zwMbs-IcHpypZPlco',
    appId: '1:1425969683:android:6c696393d2e06f871b25e6',
    messagingSenderId: '1425969683',
    projectId: 'mentorhub-82a2b',
    storageBucket: 'mentorhub-82a2b.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAGwHMpi1T46jINxmMOjzoFWb05x1uyAbs',
    appId: '1:1425969683:ios:5f91625dae1726571b25e6',
    messagingSenderId: '1425969683',
    projectId: 'mentorhub-82a2b',
    storageBucket: 'mentorhub-82a2b.firebasestorage.app',
    androidClientId:
        '1425969683-gd3n49eo85qksqme29h1ov6olir28hfc.apps.googleusercontent.com',
    iosClientId:
        '1425969683-hnhedn4d3i29ftnhfv75pmlshgaf61vf.apps.googleusercontent.com',
    iosBundleId: 'com.example.mentorshipApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAGwHMpi1T46jINxmMOjzoFWb05x1uyAbs',
    appId: '1:1425969683:ios:5f91625dae1726571b25e6',
    messagingSenderId: '1425969683',
    projectId: 'mentorhub-82a2b',
    storageBucket: 'mentorhub-82a2b.firebasestorage.app',
    androidClientId:
        '1425969683-gd3n49eo85qksqme29h1ov6olir28hfc.apps.googleusercontent.com',
    iosClientId:
        '1425969683-hnhedn4d3i29ftnhfv75pmlshgaf61vf.apps.googleusercontent.com',
    iosBundleId: 'com.example.mentorshipApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDrr6vl_1QCaqghxnNWE8KEo4CgiJ-Gj_g',
    appId: '1:1425969683:web:8198a47dc83671581b25e6',
    messagingSenderId: '1425969683',
    projectId: 'mentorhub-82a2b',
    authDomain: 'mentorhub-82a2b.firebaseapp.com',
    storageBucket: 'mentorhub-82a2b.firebasestorage.app',
  );
}
