import 'dart:io';
import 'package:flutter/material.dart';
import 'package:flutter_riverpod/flutter_riverpod.dart';
import 'package:go_router/go_router.dart';
import 'package:intl/intl.dart';
import 'package:file_picker/file_picker.dart';
import 'package:speech_to_text/speech_to_text.dart' as stt;
import 'package:screen_protector/screen_protector.dart';
import 'package:firebase_storage/firebase_storage.dart';
import 'package:cloud_firestore/cloud_firestore.dart';

import '../theme/antigravity_theme.dart';
import '../models/chat.dart';
import '../models/message.dart';
import '../providers/app_providers.dart';

class ChatDetailScreen extends ConsumerStatefulWidget {
  final Chat chat;

  const ChatDetailScreen({super.key, required this.chat});

  @override
  ConsumerState<ChatDetailScreen> createState() => _ChatDetailScreenState();
}

class _ChatDetailScreenState extends ConsumerState<ChatDetailScreen> {
  final TextEditingController _messageController = TextEditingController();
  final ScrollController _scrollController = ScrollController();
  
  late stt.SpeechToText _speech;
  bool _isListening = false;
  bool _allowsVideo = false;
  bool _isUploading = false;
  
  String get _currentUserId => ref.read(currentUserProvider).value?.id ?? '';
  String get _otherUserId => widget.chat.participantIds.firstWhere(
        (id) => id != _currentUserId,
        orElse: () => '',
      );

  @override
  void initState() {
    super.initState();
    _speech = stt.SpeechToText();
    _enableScreenProtection();
    _checkVideoPreferences();
  }

  Future<void> _enableScreenProtection() async {
    await ScreenProtector.preventScreenshotOn();
  }

  Future<void> _checkVideoPreferences() async {
    if (_otherUserId.isEmpty) return;
    try {
      final doc = await FirebaseFirestore.instance.collection('users').doc(_otherUserId).get();
      if (doc.exists) {
        final data = doc.data()!;
        final prefs = data['preferences'] as Map<String, dynamic>?;
        if (mounted) {
          setState(() {
            _allowsVideo = prefs?['allowsVideo'] == true;
          });
        }
      }
    } catch (e) {
      debugPrint('Error checking video preferences: $e');
    }
  }

  @override
  void dispose() {
    ScreenProtector.preventScreenshotOff();
    _messageController.dispose();
    _scrollController.dispose();
    super.dispose();
  }

  Future<void> _sendMessage({String? attachmentUrl, String? attachmentName, String? attachmentSize}) async {
    final text = _messageController.text.trim();
    if (text.isEmpty && attachmentUrl == null) return;

    final repo = ref.read(chatRepositoryProvider);
    _messageController.clear();
    
    // Auto-scroll to bottom
    if (_scrollController.hasClients) {
      _scrollController.animateTo(
        0.0,
        curve: Curves.easeOut,
        duration: const Duration(milliseconds: 300),
      );
    }

    try {
      final msg = Message(
        id: '', // Generated by repo
        chatId: widget.chat.id,
        senderId: _currentUserId,
        content: text,
        timestamp: DateTime.now(),
        attachmentUrl: attachmentUrl,
        attachmentName: attachmentName,
        attachmentSize: attachmentSize,
      );
      await repo.sendMessage(widget.chat.id, msg).timeout(const Duration(seconds: 10));
    } catch (e) {
      if (mounted) {
        ScaffoldMessenger.of(context).showSnackBar(
          SnackBar(content: Text('Failed to send: $e'), backgroundColor: Colors.red),
        );
      }
    }
  }

  Future<void> _pickAndUploadFile() async {
    try {
      final result = await FilePicker.platform.pickFiles(
        type: FileType.custom,
        allowedExtensions: ['pdf', 'doc', 'docx', 'jpg', 'png'],
      );

      if (result != null && result.files.single.path != null) {
        setState(() => _isUploading = true);
        
        final file = File(result.files.single.path!);
        final fileName = result.files.single.name;
        final fileSize = '${(result.files.single.size / 1024 / 1024).toStringAsFixed(1)} MB';
        final extension = result.files.single.extension?.toUpperCase() ?? 'FILE';
        
        final storageRef = FirebaseStorage.instance
            .ref()
            .child('chat_attachments')
            .child(widget.chat.id)
            .child('${DateTime.now().millisecondsSinceEpoch}_$fileName');
            
        final uploadTask = await storageRef.putFile(file);
        final downloadUrl = await uploadTask.ref.getDownloadURL();
        
        await _sendMessage(
          attachmentUrl: downloadUrl,
          attachmentName: fileName,
          attachmentSize: '$fileSize • $extension',
        );
      }
    } catch (e) {
      if (mounted) {
        ScaffoldMessenger.of(context).showSnackBar(
          SnackBar(content: Text('Upload failed: $e'), backgroundColor: Colors.red),
        );
      }
    } finally {
      if (mounted) setState(() => _isUploading = false);
    }
  }

  Future<void> _listen() async {
    if (!_isListening) {
      bool available = await _speech.initialize();
      if (available) {
        setState(() => _isListening = true);
        _speech.listen(
          onResult: (val) => setState(() {
            _messageController.text = val.recognizedWords;
          }),
        );
      }
    } else {
      setState(() => _isListening = false);
      _speech.stop();
    }
  }

  @override
  Widget build(BuildContext context) {
    final messagesStream = ref.watch(chatMessagesProvider(widget.chat.id));

    return GestureDetector(
      onTap: () => FocusScope.of(context).unfocus(),
      child: Scaffold(
        backgroundColor: AntigravityTheme.pureBlack,
        appBar: AppBar(
          backgroundColor: AntigravityTheme.pureBlack,
          elevation: 0,
          leading: IconButton(
            icon: const Icon(Icons.arrow_back_ios_new, color: Colors.white, size: 20),
            onPressed: () => context.pop(),
          ),
          titleSpacing: 0,
          title: Row(
            children: [
              Stack(
                children: [
                  Container(
                    width: 40,
                    height: 40,
                    decoration: BoxDecoration(
                      color: AntigravityTheme.midnightBlue,
                      shape: BoxShape.circle,
                      border: Border.all(color: Colors.white10),
                    ),
                    child: Center(
                      child: Text(
                        widget.chat.otherUserName.isNotEmpty 
                            ? widget.chat.otherUserName[0].toUpperCase() 
                            : '?',
                        style: const TextStyle(color: Colors.white, fontWeight: FontWeight.bold),
                      ),
                    ),
                  ),
                  Positioned(
                    right: 0,
                    bottom: 0,
                    child: Container(
                      width: 12,
                      height: 12,
                      decoration: BoxDecoration(
                        color: AntigravityTheme.neonGreen,
                        shape: BoxShape.circle,
                        border: Border.all(color: AntigravityTheme.pureBlack, width: 2),
                      ),
                    ),
                  ),
                ],
              ),
              const SizedBox(width: 12),
              Column(
                crossAxisAlignment: CrossAxisAlignment.start,
                children: [
                  Text(
                    widget.chat.otherUserName.isEmpty ? 'User' : widget.chat.otherUserName,
                    style: const TextStyle(
                      color: Colors.white,
                      fontWeight: FontWeight.bold,
                      fontSize: 16,
                      fontFamily: 'Outfit',
                    ),
                  ),
                  const Text(
                    'ONLINE',
                    style: TextStyle(
                      color: AntigravityTheme.textSecondary,
                      fontSize: 10,
                      fontWeight: FontWeight.bold,
                      letterSpacing: 0.5,
                    ),
                  ),
                ],
              ),
            ],
          ),
          actions: [
            if (_allowsVideo)
              IconButton(
                icon: const Icon(Icons.videocam_outlined, color: Colors.white, size: 22),
                onPressed: () {
                  final currentUser = ref.read(currentUserProvider).value;
                  context.push(
                    Uri(
                      path: '/video-call',
                      queryParameters: {
                        'callId': widget.chat.id,
                        'currentUserId': currentUser?.id ?? '',
                        'currentUserName': currentUser?.name ?? 'User',
                      },
                    ).toString(),
                  );
                },
              ),
            IconButton(icon: const Icon(Icons.more_vert, color: Colors.white, size: 22), onPressed: () {}),
            const SizedBox(width: 8),
          ],
        ),
        body: Column(
          children: [
            Expanded(
              child: messagesStream.when(
                data: (messages) {
                  if (messages.isEmpty) {
                    return const Center(
                      child: Text('Start the conversation!', style: TextStyle(color: Colors.white54)),
                    );
                  }
                  return ListView.builder(
                    controller: _scrollController,
                    reverse: true,
                    padding: const EdgeInsets.all(20),
                    itemCount: messages.length,
                    itemBuilder: (context, index) {
                      final msg = messages[index];
                      final isMe = msg.senderId == _currentUserId;
                      // Just simple formatting for time
                      final timeStr = DateFormat('h:mm a').format(msg.timestamp);

                      if (msg.attachmentUrl != null) {
                        return Padding(
                          padding: const EdgeInsets.only(bottom: 24),
                          child: _buildAttachmentMessage(
                            name: msg.attachmentName ?? 'File',
                            sizeLine: msg.attachmentSize ?? 'Unknown size',
                            isMe: isMe,
                            time: timeStr,
                          ),
                        );
                      }

                      return Padding(
                        padding: const EdgeInsets.only(bottom: 24),
                        child: isMe 
                            ? _buildSentMessage(message: msg.content, time: timeStr)
                            : _buildReceivedMessage(message: msg.content, time: timeStr),
                      );
                    },
                  );
                },
                loading: () => const Center(child: CircularProgressIndicator(color: AntigravityTheme.electricPurple)),
                error: (e, _) => Center(child: Text('Error loading messages: $e', style: const TextStyle(color: Colors.red))),
              ),
            ),
            if (_isUploading)
              const Padding(
                padding: EdgeInsets.symmetric(vertical: 8.0),
                child: Center(child: CircularProgressIndicator(color: AntigravityTheme.electricPurple)),
              ),
            _buildBottomInputArea(context),
          ],
        ),
      ),
    );
  }

  Widget _buildReceivedMessage({required String message, required String time}) {
    return Align(
      alignment: Alignment.centerLeft,
      child: Column(
        crossAxisAlignment: CrossAxisAlignment.start,
        children: [
          Container(
            constraints: const BoxConstraints(maxWidth: 280),
            padding: const EdgeInsets.all(16),
            decoration: BoxDecoration(
              color: AntigravityTheme.midnightBlue,
              borderRadius: const BorderRadius.only(
                topLeft: Radius.circular(20),
                topRight: Radius.circular(20),
                bottomRight: Radius.circular(20),
                bottomLeft: Radius.circular(4),
              ),
              border: Border.all(color: Colors.white.withValues(alpha: 0.05)),
            ),
            child: Text(
              message,
              style: const TextStyle(color: Colors.white, height: 1.4, fontSize: 14),
            ),
          ),
          const SizedBox(height: 6),
          Padding(
            padding: const EdgeInsets.only(left: 4),
            child: Text(time, style: const TextStyle(color: AntigravityTheme.textSecondary, fontSize: 10)),
          ),
        ],
      ),
    );
  }

  Widget _buildSentMessage({required String message, required String time}) {
    return Align(
      alignment: Alignment.centerRight,
      child: Column(
        crossAxisAlignment: CrossAxisAlignment.end,
        children: [
          Container(
            constraints: const BoxConstraints(maxWidth: 280),
            padding: const EdgeInsets.all(16),
            decoration: const BoxDecoration(
              gradient: LinearGradient(
                colors: [AntigravityTheme.electricPurple, Color(0xFF6D28D9)],
                begin: Alignment.topLeft,
                end: Alignment.bottomRight,
              ),
              borderRadius: BorderRadius.only(
                topLeft: Radius.circular(20),
                topRight: Radius.circular(20),
                bottomLeft: Radius.circular(20),
                bottomRight: Radius.circular(4),
              ),
            ),
            child: Text(
              message,
              style: const TextStyle(color: Colors.white, height: 1.4, fontSize: 14, fontWeight: FontWeight.w500),
            ),
          ),
          const SizedBox(height: 6),
          Padding(
            padding: const EdgeInsets.only(right: 4),
            child: Row(
              mainAxisSize: MainAxisSize.min,
              children: [
                Text(time, style: const TextStyle(color: AntigravityTheme.textSecondary, fontSize: 10)),
                const SizedBox(width: 4),
                const Icon(Icons.done_all, color: AntigravityTheme.neonGreen, size: 14),
              ],
            ),
          ),
        ],
      ),
    );
  }

  Widget _buildAttachmentMessage({
    required String name, 
    required String sizeLine, 
    required bool isMe,
    required String time,
  }) {
    return Align(
      alignment: isMe ? Alignment.centerRight : Alignment.centerLeft,
      child: Column(
        crossAxisAlignment: isMe ? CrossAxisAlignment.end : CrossAxisAlignment.start,
        children: [
          Container(
            width: 280,
            padding: const EdgeInsets.all(12),
            decoration: BoxDecoration(
              color: isMe ? AntigravityTheme.electricPurple.withValues(alpha: 0.2) : AntigravityTheme.midnightBlue,
              borderRadius: BorderRadius.circular(16),
              border: Border.all(color: Colors.white.withValues(alpha: 0.1)),
            ),
            child: Row(
              children: [
                Container(
                  padding: const EdgeInsets.all(10),
                  decoration: BoxDecoration(
                    color: Colors.red.withValues(alpha: 0.1),
                    borderRadius: BorderRadius.circular(12),
                  ),
                  child: const Icon(Icons.picture_as_pdf, color: Color(0xFFEF4444)),
                ),
                const SizedBox(width: 12),
                Expanded(
                  child: Column(
                    crossAxisAlignment: CrossAxisAlignment.start,
                    children: [
                      Text(
                        name,
                        style: const TextStyle(color: Colors.white, fontWeight: FontWeight.bold, fontSize: 13),
                        overflow: TextOverflow.ellipsis,
                      ),
                      const SizedBox(height: 4),
                      Text(sizeLine, style: const TextStyle(color: AntigravityTheme.textSecondary, fontSize: 11)),
                    ],
                  ),
                ),
                const Icon(Icons.download_rounded, color: Colors.white60, size: 20),
              ],
            ),
          ),
          const SizedBox(height: 6),
          Padding(
            padding: EdgeInsets.only(left: isMe ? 0 : 4, right: isMe ? 4 : 0),
            child: Text(time, style: const TextStyle(color: AntigravityTheme.textSecondary, fontSize: 10)),
          ),
        ],
      ),
    );
  }

  Widget _buildBottomInputArea(BuildContext context) {
    return Container(
      padding: EdgeInsets.only(
        left: 20, right: 20, top: 12,
        bottom: MediaQuery.of(context).padding.bottom + 12,
      ),
      decoration: BoxDecoration(
        color: AntigravityTheme.pureBlack,
        border: Border(top: BorderSide(color: Colors.white.withValues(alpha: 0.05))),
      ),
      child: Row(
        children: [
          GestureDetector(
            onTap: _pickAndUploadFile,
            child: Container(
              padding: const EdgeInsets.all(10),
              decoration: const BoxDecoration(
                color: AntigravityTheme.midnightBlue,
                shape: BoxShape.circle,
              ),
              child: const Icon(Icons.attach_file, color: Colors.white, size: 20),
            ),
          ),
          const SizedBox(width: 12),
          Expanded(
            child: Container(
              padding: const EdgeInsets.symmetric(horizontal: 16),
              decoration: BoxDecoration(
                color: AntigravityTheme.midnightBlue,
                borderRadius: BorderRadius.circular(24),
                border: Border.all(color: Colors.white.withValues(alpha: 0.05)),
              ),
              child: Row(
                children: [
                  Expanded(
                    child: TextField(
                      controller: _messageController,
                      style: const TextStyle(color: Colors.white, fontSize: 14),
                      decoration: InputDecoration(
                        hintText: _isListening ? 'Listening...' : 'Type a message...',
                        hintStyle: const TextStyle(color: Colors.white24),
                        border: InputBorder.none,
                      ),
                      onSubmitted: (_) => _sendMessage(),
                    ),
                  ),
                  IconButton(
                    icon: Icon(
                      _isListening ? Icons.mic : Icons.mic_none, 
                      color: _isListening ? Colors.redAccent : Colors.white54
                    ),
                    onPressed: _listen,
                  ),
                  IconButton(
                    icon: const Icon(Icons.send_rounded, color: AntigravityTheme.electricPurple),
                    onPressed: () => _sendMessage(),
                  ),
                ],
              ),
            ),
          ),
        ],
      ),
    );
  }
}
